version: "{build}"

clone_folder: c:\gopath\src\github.com\manifoldco\torus-cli

platform:
  - x64

environment:
  GOPATH: c:\gopath
  GOVERSION: 1.9.1
  DEPVERSION: 0.3.2

init:
  - git config --global core.autocrlf input
  - cinst zip                                # zip binary from chocolatey

install:
  - set PATH=%WIX%\bin;%PATH%                # need this on appveyor
  - rmdir c:\go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go%GOVERSION%.windows-amd64.msi
  - msiexec /i go%GOVERSION%.windows-amd64.msi /q
  - set Path=c:\go\bin;c:\gopath\bin;%Path%
  - go version
  - go env
  - C:\MinGW\bin\mingw32-make bootstrap-windows
  - set PATH=C:\Program Files\go-msi\;%PATH% # need this on appveyor


build_script:
  - C:\MinGW\bin\mingw32-make msi

test_script:
  - FOR /f "" %%G in ('go list ./... ^| find /i /v "/vendor/"') DO (go test -run=. -bench=. -v %%G)
